import { db } from '@/db';
import { inventory } from '@/db/schema';

async function main() {
    const sampleInventory = [
        // Pharmacy 1 - Good stock levels, mix of categories
        {
            pharmacyId: 1,
            medicineId: 1,
            quantity: 150,
            price: 54.99,
            discountPercentage: 5,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 3,
            quantity: 80,
            price: 32.99,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 5,
            quantity: 120,
            price: 22.50,
            discountPercentage: 10,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 7,
            quantity: 95,
            price: 8.99,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 9,
            quantity: 60,
            price: 16.50,
            discountPercentage: 5,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 11,
            quantity: 110,
            price: 13.75,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 13,
            quantity: 0,
            price: 21.99,
            discountPercentage: 0,
            isAvailable: 0,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 15,
            quantity: 85,
            price: 10.99,
            discountPercentage: 8,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 17,
            quantity: 140,
            price: 27.50,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 19,
            quantity: 75,
            price: 14.25,
            discountPercentage: 5,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 2,
            quantity: 100,
            price: 43.99,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 1,
            medicineId: 8,
            quantity: 65,
            price: 18.75,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },

        // Pharmacy 2 - Highest variety, some promotional discounts
        {
            pharmacyId: 2,
            medicineId: 1,
            quantity: 130,
            price: 52.99,
            discountPercentage: 8,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 2,
            quantity: 90,
            price: 41.50,
            discountPercentage: 15,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 4,
            quantity: 110,
            price: 26.99,
            discountPercentage: 5,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 6,
            quantity: 85,
            price: 33.75,
            discountPercentage: 20,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 8,
            quantity: 145,
            price: 17.99,
            discountPercentage: 10,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 10,
            quantity: 70,
            price: 38.50,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 12,
            quantity: 160,
            price: 11.25,
            discountPercentage: 5,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 14,
            quantity: 95,
            price: 16.99,
            discountPercentage: 12,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 16,
            quantity: 120,
            price: 23.75,
            discountPercentage: 25,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 18,
            quantity: 0,
            price: 19.99,
            discountPercentage: 0,
            isAvailable: 0,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 20,
            quantity: 105,
            price: 29.50,
            discountPercentage: 8,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 3,
            quantity: 75,
            price: 34.99,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 7,
            quantity: 140,
            price: 8.50,
            discountPercentage: 15,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 11,
            quantity: 88,
            price: 14.25,
            discountPercentage: 5,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 2,
            medicineId: 15,
            quantity: 125,
            price: 11.50,
            discountPercentage: 10,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },

        // Pharmacy 3 - Lower stock levels, focus on common medicines
        {
            pharmacyId: 3,
            medicineId: 1,
            quantity: 45,
            price: 56.99,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 2,
            quantity: 30,
            price: 44.99,
            discountPercentage: 5,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 5,
            quantity: 55,
            price: 24.99,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 7,
            quantity: 0,
            price: 9.50,
            discountPercentage: 0,
            isAvailable: 0,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 9,
            quantity: 40,
            price: 17.25,
            discountPercentage: 8,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 11,
            quantity: 65,
            price: 13.99,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 13,
            quantity: 35,
            price: 22.50,
            discountPercentage: 5,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 15,
            quantity: 50,
            price: 12.25,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 17,
            quantity: 25,
            price: 28.99,
            discountPercentage: 10,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
        {
            pharmacyId: 3,
            medicineId: 19,
            quantity: 60,
            price: 15.50,
            discountPercentage: 0,
            isAvailable: 1,
            lastUpdated: new Date().toISOString(),
        },
    ];

    await db.insert(inventory).values(sampleInventory);
    
    console.log('✅ Inventory seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});