import { db } from '@/db';
import { medicines } from '@/db/schema';

async function main() {
    const sampleMedicines = [
        // Prescription medicines (6)
        {
            name: 'Paracetamol',
            brand: 'Tylenol',
            saltComposition: 'Paracetamol 500mg',
            category: 'prescription',
            description: 'Pain reliever and fever reducer used for headaches, muscle aches, and mild to moderate pain.',
            manufacturer: 'Johnson & Johnson',
            unit: '20 tablets',
            price: 18.99,
            requiresPrescription: true,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Amoxicillin',
            brand: 'Amoxil',
            saltComposition: 'Amoxicillin 500mg',
            category: 'prescription',
            description: 'Antibiotic used to treat bacterial infections including respiratory tract infections.',
            manufacturer: 'GSK',
            unit: '15 capsules',
            price: 32.50,
            requiresPrescription: true,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Metformin',
            brand: 'Glucophage',
            saltComposition: 'Metformin Hydrochloride 500mg',
            category: 'prescription',
            description: 'First-line medication for type 2 diabetes that helps control blood sugar levels.',
            manufacturer: 'Bristol-Myers Squibb',
            unit: '30 tablets',
            price: 28.75,
            requiresPrescription: true,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Atorvastatin',
            brand: 'Lipitor',
            saltComposition: 'Atorvastatin Calcium 20mg',
            category: 'prescription',
            description: 'Cholesterol-lowering medication used to prevent cardiovascular disease.',
            manufacturer: 'Pfizer',
            unit: '30 tablets',
            price: 42.99,
            requiresPrescription: true,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Lisinopril',
            brand: 'Zestril',
            saltComposition: 'Lisinopril 10mg',
            category: 'prescription',
            description: 'ACE inhibitor used to treat high blood pressure and heart failure.',
            manufacturer: 'AstraZeneca',
            unit: '30 tablets',
            price: 24.50,
            requiresPrescription: true,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Omeprazole',
            brand: 'Prilosec',
            saltComposition: 'Omeprazole 20mg',
            category: 'prescription',
            description: 'Proton pump inhibitor used to treat gastroesophageal reflux disease and stomach ulcers.',
            manufacturer: 'AstraZeneca',
            unit: '28 capsules',
            price: 35.99,
            requiresPrescription: true,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // OTC medicines (5)
        {
            name: 'Ibuprofen',
            brand: 'Advil',
            saltComposition: 'Ibuprofen 200mg',
            category: 'otc',
            description: 'Non-steroidal anti-inflammatory drug for pain relief and fever reduction.',
            manufacturer: 'Pfizer',
            unit: '24 tablets',
            price: 12.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Cetirizine',
            brand: 'Zyrtec',
            saltComposition: 'Cetirizine Hydrochloride 10mg',
            category: 'otc',
            description: 'Antihistamine used to relieve allergy symptoms like runny nose and watery eyes.',
            manufacturer: 'Johnson & Johnson',
            unit: '30 tablets',
            price: 15.50,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Loperamide',
            brand: 'Imodium',
            saltComposition: 'Loperamide Hydrochloride 2mg',
            category: 'otc',
            description: 'Anti-diarrheal medication that slows down gut movement.',
            manufacturer: 'Johnson & Johnson',
            unit: '12 capsules',
            price: 9.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Ranitidine',
            brand: 'Zantac',
            saltComposition: 'Ranitidine Hydrochloride 150mg',
            category: 'otc',
            description: 'H2 blocker used to reduce stomach acid and treat heartburn.',
            manufacturer: 'GSK',
            unit: '20 tablets',
            price: 11.75,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Loratadine',
            brand: 'Claritin',
            saltComposition: 'Loratadine 10mg',
            category: 'otc',
            description: 'Long-acting antihistamine for 24-hour allergy relief without drowsiness.',
            manufacturer: 'Bayer',
            unit: '30 tablets',
            price: 18.50,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Supplements (3)
        {
            name: 'Vitamin D3',
            brand: 'Nature Made',
            saltComposition: 'Cholecalciferol 1000IU',
            category: 'supplement',
            description: 'Essential vitamin supplement for bone health and immune system support.',
            manufacturer: 'Pharmavite',
            unit: '100 softgels',
            price: 14.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Omega-3 Fish Oil',
            brand: 'Nordic Naturals',
            saltComposition: 'EPA 650mg, DHA 450mg',
            category: 'supplement',
            description: 'Premium fish oil supplement for heart and brain health.',
            manufacturer: 'Nordic Naturals',
            unit: '60 softgels',
            price: 28.50,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Multivitamin',
            brand: 'Centrum',
            saltComposition: 'Vitamins A, C, D, E, B-Complex, Minerals',
            category: 'supplement',
            description: 'Complete daily multivitamin with essential vitamins and minerals.',
            manufacturer: 'GSK',
            unit: '100 tablets',
            price: 22.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Devices (2)
        {
            name: 'Blood Pressure Monitor',
            brand: 'Omron',
            saltComposition: 'N/A',
            category: 'device',
            description: 'Digital blood pressure monitor with automatic inflation and memory storage.',
            manufacturer: 'Omron Healthcare',
            unit: '1 device',
            price: 79.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Blood Glucose Meter',
            brand: 'Accu-Chek',
            saltComposition: 'N/A',
            category: 'device',
            description: 'Accurate blood glucose monitoring system with fast results.',
            manufacturer: 'Roche',
            unit: '1 kit',
            price: 89.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // First aid items (2)
        {
            name: 'First Aid Kit',
            brand: 'Johnson & Johnson',
            saltComposition: 'N/A',
            category: 'first_aid',
            description: 'Complete first aid kit with bandages, antiseptic wipes, and medical supplies.',
            manufacturer: 'Johnson & Johnson',
            unit: '1 kit',
            price: 24.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            name: 'Adhesive Bandages',
            brand: 'Band-Aid',
            saltComposition: 'N/A',
            category: 'first_aid',
            description: 'Flexible adhesive bandages for minor cuts and scrapes.',
            manufacturer: 'Johnson & Johnson',
            unit: '100 bandages',
            price: 16.50,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Baby care (1)
        {
            name: 'Baby Wipes',
            brand: 'Huggies',
            saltComposition: 'N/A',
            category: 'baby_care',
            description: 'Gentle baby wipes for sensitive skin with aloe and vitamin E.',
            manufacturer: 'Kimberly-Clark',
            unit: '80 wipes',
            price: 11.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Personal care (1)
        {
            name: 'Hand Sanitizer',
            brand: 'Purell',
            saltComposition: 'Ethyl Alcohol 70%',
            category: 'personal_care',
            description: 'Advanced hand sanitizer gel that kills 99.99% of germs.',
            manufacturer: 'GOJO Industries',
            unit: '500ml',
            price: 8.99,
            requiresPrescription: false,
            imageUrl: null,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
    ];

    await db.insert(medicines).values(sampleMedicines);
    
    console.log('✅ Medicines seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});